// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnouncementAction } from "./AnnouncementAction";

export type AnnouncementInfo = {
  id: string;
  title: string;
  message: string;
  type: string;
  priority: string;
  dismissible: boolean;
  start_at: string;
  end_at: string;
  action: AnnouncementAction | null;
};
