// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

export type AppSettings = { theme: Theme, show_audit_log: boolean, auto_scan_repos: boolean, };
