// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SmartSwitchingSettings } from "./SmartSwitchingSettings";
import type { Theme } from "./Theme";

export type AppSettings = { theme: Theme, show_audit_log: boolean, auto_scan_repos: boolean, 
/**
 * Smart Identity Switching (Sprint 6). `#[serde(default)]` keeps settings
 * files written before this field was introduced loadable.
 */
smart_switching: SmartSwitchingSettings, };
