// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuditEntry = { id: string, timestamp: string, action: string, profile_id: string | null, repo_path: string | null, };
