// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AnnouncementInfo } from "./AnnouncementInfo";

/**
 * Client state fetched from the `GitPersona` server once at startup.
 */
export type BootstrapData = {
  announcements: Array<AnnouncementInfo>;
  /**
   * Enabled feature flags keyed by their kebab-case identifier.
   */
  feature_flags: { [key in string]?: boolean };
  /**
   * Whether the server considers the current update mandatory.
   * `None` when the server is unreachable or returns no update info.
   */
  force_update: boolean | null;
};
