// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a platform-specific capability is currently usable. `Planned`
 * distinguishes a capability that is intentionally on the roadmap (so the UI
 * can describe it honestly) from one that simply does not apply (`Unavailable`).
 */
export type CapabilityStatus = "Available" | "Planned" | "Unavailable";
