// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardMode } from "./GuardMode";
import type { RepoGuardStatus } from "./RepoGuardStatus";

/**
 * Aggregate Commit Guard status for the dashboard/settings view.
 */
export type CommitGuardStatus = {
  enabled: boolean;
  mode: GuardMode;
  auto_protect: boolean;
  /**
   * Number of tracked repositories with the managed hook installed.
   */
  protected_count: number;
  repos: Array<RepoGuardStatus>;
};
