// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardMode } from "./GuardMode";

/**
 * Configuration for Commit Guard. Read by the service that installs and repairs
 * per-repository hooks; the installed hook itself reads the mode from the
 * repository's local Git config so it stays self-contained and offline.
 */
export type CommitGuardSettings = {
  /**
   * Master switch. When off, no new hooks are installed and status reports
   * the feature as disabled. Existing installed hooks are left in place until
   * explicitly removed, but a disabled repo marker makes them a no-op.
   */
  enabled: boolean;
  /**
   * Default behavior on a detected mismatch for newly protected repositories.
   */
  mode: GuardMode;
  /**
   * Automatically install the hook when a profile is assigned to a repository.
   */
  auto_protect: boolean;
};
