// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Protocol } from "./Protocol";

/**
 * Metadata for a stored HTTPS Git credential.
 *
 * Holds **references and metadata only**. The secret lives exclusively in the
 * OS credential vault (Windows Credential Manager, macOS Keychain, or Linux
 * Secret Service) and is never a field here.
 */
export type Credential = {
  id: string;
  profile_id: string | null;
  host: string;
  protocol: Protocol;
  username: string;
  created_at: string;
  updated_at: string;
  last_used: string | null;
  /**
   * Whether a reveal PIN is set. `true` means the token can be read back via
   * the PIN-gated reveal flow. The PIN's Argon2 hash lives in the credential
   * store's side map, never here and never on the wire. `#[serde(default)]`
   * keeps pre-PIN records deserializable.
   */
  has_pin: boolean;
};
