// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Protocol } from "./Protocol";

/**
 * Metadata for a stored HTTPS Git credential.
 *
 * Holds **references and metadata only**. The secret lives exclusively in the
 * OS credential vault (Windows Credential Manager) and is never a field here.
 */
export type Credential = { id: string, profile_id: string | null, host: string, protocol: Protocol, username: string, created_at: string, updated_at: string, last_used: string | null, };
