// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A Git credential the OS vault already holds for a supported host. Only the
 * username is read — the secret is never touched during detection.
 */
export type DetectedCredential = { host: string; username: string };
