// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshAlgorithm } from "./SshAlgorithm";

/**
 * A private key discovered in `~/.ssh` during onboarding. Holds references and
 * metadata only — never key material. Not yet persisted; the user selects which
 * to import.
 */
export type DetectedSshKey = {
  private_key_path: string;
  algorithm: SshAlgorithm;
  fingerprint: string;
  comment: string | null;
};
