// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Git identity read from the user's global config, offered as a profile to
 * create during first-run onboarding. Any field may be absent.
 */
export type DetectedIdentity = {
  name: string | null;
  email: string | null;
  signing_key: string | null;
};
