// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How Commit Guard reacts when the active Git identity does not match the
 * repository's expected profile.
 */
export type GuardMode = "Warn" | "Block";
