// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The install state of the managed `pre-commit` hook in one repository.
 */
export type HookState = "NotInstalled" | "Managed" | "ManagedChained" | "Foreign" | "Unsupported";
