// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The host operating system family, as GitPersona's platform abstraction
 * distinguishes it. `Other` covers targets with no native secure-storage
 * integration (the no-op vault).
 */
export type PlatformOs = "Windows" | "Macos" | "Linux" | "Other";
