// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CapabilityStatus } from "./CapabilityStatus";
import type { PlatformOs } from "./PlatformOs";

/**
 * The credential-related capabilities of the current platform, derived at
 * compile time from the same `cfg` gating that selects the concrete
 * [`CredentialVault`](crate::domain::ports::CredentialVault) implementation in
 * `state.rs`. The frontend consumes this to render only actions that can
 * actually succeed, so a user never sees a primary action that is guaranteed
 * to fail on their OS.
 *
 * The three capabilities are deliberately independent — secure storage does
 * **not** imply automatic Git HTTPS credential integration:
 *
 * - `credential_vault` — secrets can be stored in the OS-native secure store.
 * - `native_credential_manager` — GitPersona can open a native credential
 *   management UI (only Windows' Credential Manager today).
 * - `git_credential_integration` — stored secrets are automatically consumed
 *   by Git's HTTPS credential helper. `Available` only on Windows, whose vault
 *   writes under Git's `wincred` target convention; `Planned` on macOS/Linux,
 *   where the keyring vault stores under GitPersona's own namespace.
 */
export type PlatformCapabilities = {
  os: PlatformOs;
  credential_vault: CapabilityStatus;
  native_credential_manager: CapabilityStatus;
  git_credential_integration: CapabilityStatus;
};
