// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Transport protocol for a Git credential. Sprint 5 handles HTTPS only; the
 * enum exists so SSH/other schemes can be added without a data migration.
 */
export type Protocol = "Https";
