// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Repo = {
  id: string;
  name: string;
  path: string;
  git_root: string;
  active_branch: string | null;
  active_profile_id: string | null;
  remote_origin: string | null;
  last_opened: string | null;
  favorite: boolean;
  detected_at: string;
  /**
   * The user-defined group ("ecosystem") this repo belongs to, if any.
   * `#[serde(default)]` keeps pre-grouping records deserializable.
   */
  group_id: string | null;
  /**
   * Whether `path` still exists on disk. Derived at read time and recomputed
   * on every load, so the UI can flag repositories whose folder was moved or
   * deleted. `#[serde(default)]` keeps pre-existing records deserializable.
   */
  path_exists: boolean;
};
