// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Repo = { id: string, name: string, path: string, git_root: string, active_branch: string | null, active_profile_id: string | null, remote_origin: string | null, last_opened: string | null, favorite: boolean, detected_at: string, };
