// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GuardMode } from "./GuardMode";
import type { HookState } from "./HookState";

/**
 * Per-repository Commit Guard status, surfaced in the UI so the user can see
 * exactly which repositories are protected and how.
 */
export type RepoGuardStatus = {
  repo_id: string;
  git_root: string;
  repo_name: string;
  hook_state: HookState;
  /**
   * `true` when the managed hook is installed (`Managed` or `ManagedChained`).
   */
  protected: boolean;
  /**
   * The mode recorded in the repo's local config, when protected.
   */
  mode: GuardMode | null;
  /**
   * The profile this repository is expected to commit as, if one can be
   * resolved (rule match or repository assignment). `None` means no expected
   * profile — the guard allows commits (never blocks on the unknown).
   */
  expected_profile_id: string | null;
  expected_label: string | null;
  /**
   * The `user.email` a commit here would currently use (local config, else
   * global). Lets the UI show a live match/mismatch. Never a secret.
   */
  current_email: string | null;
  /**
   * `Some(true/false)` when an expected profile is known; `None` when no
   * expected identity can be resolved (guard would allow the commit).
   */
  identity_matches: boolean | null;
};
