// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user-defined repository group — an "ecosystem" such as "Dolphin Modules"
 * that repositories can be organized under. Ordering in the UI follows the
 * stored order.
 */
export type RepoGroup = { id: string; name: string; color: string | null; created_at: string };
