// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The repository fact a rule condition inspects.
 *
 * `RemoteHost` and `Owner` are derived by parsing the remote URL and only
 * support the `Equals` operator (see [`RuleSubject::allows`]).
 */
export type RuleSubject = "RepoPath" | "RepoName" | "RemoteUrl" | "RemoteHost" | "Owner";
