// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleMatch } from "./RuleMatch";

/**
 * The result of a preview evaluation.
 */
export type RulePreviewResult = { matched: RuleMatch | null };
