// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleOperator } from "./RuleOperator";
import type { RuleSubject } from "./RuleSubject";

/**
 * A single declarative predicate: does `subject` `operator` `value` hold for a
 * repository?
 */
export type RuleCondition = { subject: RuleSubject; operator: RuleOperator; value: string };
