// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleCondition } from "./RuleCondition";

/**
 * A rule mapping a repository condition to a target profile. Rules are the
 * decision layer: they only ever *select* a profile — execution stays in the
 * existing profile-apply pipeline.
 */
export type Rule = {
  id: string;
  name: string;
  enabled: boolean;
  /**
   * Lower number = higher priority. Evaluated ascending; first match wins.
   */
  priority: number;
  target_profile_id: string;
  condition: RuleCondition;
  created_at: string;
  updated_at: string;
};
