// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RuleMatch } from "./RuleMatch";

/**
 * Aggregate figures for the dashboard widget.
 */
export type RuleSummary = { active: number; disabled: number; last_match: RuleMatch | null };
