// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Input for the preview command — the user describes a hypothetical repository
 * and sees which rule (if any) would match. Never triggers a switch.
 */
export type RulePreviewInput = { path: string; name: string; remote_url: string | null };
