// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The outcome of a successful rule resolution. Carries display metadata only —
 * consumed by the preview, the dashboard summary, and the switching audit.
 */
export type RuleMatch = { rule_id: string, rule_name: string, profile_id: string, reason: string, };
