// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The comparison a rule condition applies. Deterministic string matching only —
 * no regular expressions, globbing, or scripting.
 */
export type RuleOperator = "Contains" | "StartsWith" | "EndsWith" | "Equals";
