// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Progress emitted to the frontend while a scan traverses the filesystem.
 */
export type ScanProgress = { scanned_dirs: number, found_repos: number, };
