// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SwitchEvent } from "./SwitchEvent";

/**
 * A snapshot of the watcher/orchestrator state for the dashboard widget.
 */
export type SmartSwitchStatus = { enabled: boolean, watching: boolean, paused: boolean, repos_monitored: number, last_switch: SwitchEvent | null, started_at: string | null, };
