// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Configuration for the Smart Identity Switching engine. Read live on every
 * activation event, so a change takes effect on the next repository switch.
 */
export type SmartSwitchingSettings = { 
/**
 * Master switch: when off, the workspace watcher does not run.
 */
enabled: boolean, 
/**
 * Reserved — SSH identities are wired globally via the managed `~/.ssh/config`
 * block, so they follow the applied profile automatically. Surfaced as a
 * toggle for parity and a future per-stage gate.
 */
auto_ssh: boolean, 
/**
 * Reserved — HTTPS credentials are switched as part of the atomic profile
 * apply. Surfaced as a toggle for parity and a future per-stage gate.
 */
auto_credential: boolean, 
/**
 * Emit an in-app notification after an automatic switch.
 */
show_notification: boolean, 
/**
 * Require explicit confirmation before applying an automatic switch.
 */
confirm_before_switch: boolean, 
/**
 * Start watching automatically when the application launches.
 */
start_on_launch: boolean, };
