// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Supported SSH key algorithms. Anything else is ignored during discovery and
 * rejected on import (Sprint 4 covers ED25519 and RSA only).
 */
export type SshAlgorithm = "Ed25519" | "Rsa";
