// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SshAlgorithm } from "./SshAlgorithm";

/**
 * A managed SSH identity. Stores **references and metadata only** — private key
 * bytes are never held here, serialized, or logged.
 */
export type SshKey = {
  id: string;
  label: string;
  algorithm: SshAlgorithm;
  fingerprint: string;
  private_key_path: string;
  public_key_path: string | null;
  comment: string | null;
  assigned_profile_id: string | null;
  host_alias: string | null;
  host_name: string | null;
  created_at: string;
  imported: boolean;
  last_used: string | null;
};
