// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of evaluating one repository activation against the smart-switching
 * rules. Drives the toast/notification and dashboard state on the frontend.
 */
export type SwitchStatus = "Switched" | "AlreadyActive" | "NoAssignment" | "PendingConfirmation";
