// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SwitchStatus } from "./SwitchStatus";

/**
 * A single smart-switching event, emitted to the frontend and stored as the
 * "last automatic switch" for the dashboard. Carries only display metadata —
 * never secrets, tokens, or key material.
 */
export type SwitchEvent = {
  status: SwitchStatus;
  git_root: string;
  repo_id: string | null;
  repo_name: string | null;
  profile_id: string | null;
  profile_label: string | null;
  at: string;
};
