// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DetectedCredential } from "./DetectedCredential";
import type { DetectedIdentity } from "./DetectedIdentity";
import type { DetectedSshKey } from "./DetectedSshKey";

/**
 * The read-only result of scanning the system for existing Git setup, shown in
 * the first-run onboarding wizard.
 */
export type SystemScan = {
  identity: DetectedIdentity | null;
  ssh_keys: Array<DetectedSshKey>;
  credentials: Array<DetectedCredential>;
  /**
   * `true` when onboarding was already completed or a profile already exists —
   * the frontend uses this to avoid re-prompting.
   */
  already_onboarded: boolean;
};
