// This file is generated by `cargo test export_bindings` — do not hand-edit.

export type Theme = "Dark" | "Light" | "System";

export interface AppSettings {
  theme: Theme;
  show_audit_log: boolean;
  auto_scan_repos: boolean;
}

export interface Identity {
  name: string;
  email: string;
  signing_key?: string;
}

export interface Profile {
  id: string;
  label: string;
  identity: Identity;
  color?: string;
}

export interface Repo {
  id: string;
  name: string;
  path: string;
  git_root: string;
  active_branch: string | null;
  active_profile_id: string | null;
  remote_origin: string | null;
  last_opened: string | null;
  favorite: boolean;
  detected_at: string;
}

export interface ScanProgress {
  scanned_dirs: number;
  found_repos: number;
}

export interface AuditEntry {
  id: string;
  timestamp: string;
  action: string;
  profile_id?: string;
  repo_path?: string;
}

export type SshAlgorithm = "Ed25519" | "Rsa";

export interface SshKey {
  id: string;
  label: string;
  algorithm: SshAlgorithm;
  fingerprint: string;
  private_key_path: string;
  public_key_path: string | null;
  comment: string | null;
  assigned_profile_id: string | null;
  host_alias: string | null;
  host_name: string | null;
  created_at: string;
  imported: boolean;
  last_used: string | null;
}
