// This file is generated by `cargo test export_bindings` — do not hand-edit.

export interface BootstrapData {
  announcements: AnnouncementInfo[];
  feature_flags: Record<string, boolean>;
  force_update: boolean | null;
}

export interface AnnouncementInfo {
  id: string;
  title: string;
  message: string;
  type: string;
  priority: string;
  dismissible: boolean;
  start_at: string;
  end_at: string;
  action: AnnouncementAction | null;
}

export interface AnnouncementAction {
  label: string;
  url: string;
}

export type Theme = "Dark" | "Light" | "System";

export interface AppSettings {
  theme: Theme;
  show_audit_log: boolean;
  auto_scan_repos: boolean;
  smart_switching: SmartSwitchingSettings;
  commit_guard: CommitGuardSettings;
  onboarded: boolean;
  launch_at_startup: boolean;
  start_minimized: boolean;
  close_to_tray: boolean;
}

export interface SmartSwitchingSettings {
  enabled: boolean;
  auto_ssh: boolean;
  auto_credential: boolean;
  show_notification: boolean;
  confirm_before_switch: boolean;
  start_on_launch: boolean;
}

export type GuardMode = "Warn" | "Block";

export interface CommitGuardSettings {
  enabled: boolean;
  mode: GuardMode;
  auto_protect: boolean;
}

export type HookState =
  | "NotInstalled"
  | "Managed"
  | "ManagedChained"
  | "Foreign"
  | "Unsupported";

export interface RepoGuardStatus {
  repo_id: string;
  git_root: string;
  repo_name: string;
  hook_state: HookState;
  protected: boolean;
  mode: GuardMode | null;
  expected_profile_id: string | null;
  expected_label: string | null;
  current_email: string | null;
  identity_matches: boolean | null;
}

export interface CommitGuardStatus {
  enabled: boolean;
  mode: GuardMode;
  auto_protect: boolean;
  protected_count: number;
  repos: RepoGuardStatus[];
}

export interface Identity {
  name: string;
  email: string;
  signing_key?: string;
}

export interface Profile {
  id: string;
  label: string;
  identity: Identity;
  color?: string;
}

export interface Repo {
  id: string;
  name: string;
  path: string;
  git_root: string;
  active_branch: string | null;
  active_profile_id: string | null;
  remote_origin: string | null;
  last_opened: string | null;
  favorite: boolean;
  detected_at: string;
  group_id: string | null;
  path_exists: boolean;
}

export interface RepoGroup {
  id: string;
  name: string;
  color: string | null;
  created_at: string;
}

export interface ScanProgress {
  scanned_dirs: number;
  found_repos: number;
}

export interface AuditEntry {
  id: string;
  timestamp: string;
  action: string;
  profile_id?: string;
  repo_path?: string;
}

export type SshAlgorithm = "Ed25519" | "Rsa";

export interface SshKey {
  id: string;
  label: string;
  algorithm: SshAlgorithm;
  fingerprint: string;
  private_key_path: string;
  public_key_path: string | null;
  comment: string | null;
  assigned_profile_id: string | null;
  host_alias: string | null;
  host_name: string | null;
  created_at: string;
  imported: boolean;
  last_used: string | null;
}

export type Protocol = "Https";

export interface Credential {
  id: string;
  profile_id: string | null;
  host: string;
  protocol: Protocol;
  username: string;
  created_at: string;
  updated_at: string;
  last_used: string | null;
  has_pin: boolean;
}

export type PlatformOs = "Windows" | "Macos" | "Linux" | "Other";

export type CapabilityStatus = "Available" | "Planned" | "Unavailable";

export interface PlatformCapabilities {
  os: PlatformOs;
  credential_vault: CapabilityStatus;
  native_credential_manager: CapabilityStatus;
  git_credential_integration: CapabilityStatus;
}

export type SwitchStatus =
  | "Switched"
  | "AlreadyActive"
  | "NoAssignment"
  | "PendingConfirmation";

export interface SwitchEvent {
  status: SwitchStatus;
  git_root: string;
  repo_id: string | null;
  repo_name: string | null;
  profile_id: string | null;
  profile_label: string | null;
  at: string;
}

export interface SmartSwitchStatus {
  enabled: boolean;
  watching: boolean;
  paused: boolean;
  repos_monitored: number;
  last_switch: SwitchEvent | null;
  started_at: string | null;
}

export type RuleSubject =
  | "RepoPath"
  | "RepoName"
  | "RemoteUrl"
  | "RemoteHost"
  | "Owner";

export type RuleOperator = "Contains" | "StartsWith" | "EndsWith" | "Equals";

export interface RuleCondition {
  subject: RuleSubject;
  operator: RuleOperator;
  value: string;
}

export interface Rule {
  id: string;
  name: string;
  enabled: boolean;
  priority: number;
  target_profile_id: string;
  condition: RuleCondition;
  created_at: string;
  updated_at: string;
}

export interface RuleMatch {
  rule_id: string;
  rule_name: string;
  profile_id: string;
  reason: string;
}

export interface RulePreviewInput {
  path: string;
  name: string;
  remote_url: string | null;
}

export interface RulePreviewResult {
  matched: RuleMatch | null;
}

export interface RuleSummary {
  active: number;
  disabled: number;
  last_match: RuleMatch | null;
}

export interface DetectedIdentity {
  name: string | null;
  email: string | null;
  signing_key: string | null;
}

export interface DetectedSshKey {
  private_key_path: string;
  algorithm: SshAlgorithm;
  fingerprint: string;
  comment: string | null;
}

export interface DetectedCredential {
  host: string;
  username: string;
}

export interface SystemScan {
  identity: DetectedIdentity | null;
  ssh_keys: DetectedSshKey[];
  credentials: DetectedCredential[];
  already_onboarded: boolean;
}
